// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi KOZAN_
The API that supports my every need.


    Schemes:
      https
    Host: zhouyiyan.cn
    BasePath: /v1
    Version: 1.0.0

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
