// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "description": "The API that supports my every need.",
    "title": "KOZAN_",
    "version": "1.0.0"
  },
  "host": "zhouyiyan.cn",
  "basePath": "/v1",
  "paths": {
    "/health": {
      "get": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "health"
        ],
        "summary": "Check the health for the site.",
        "operationId": "getHealth",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/HealthStatus"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Error": {
      "required": [
        "code",
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int32"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "HealthStatus": {
      "properties": {
        "status": {
          "type": "string"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "description": "The API that supports my every need.",
    "title": "KOZAN_",
    "version": "1.0.0"
  },
  "host": "zhouyiyan.cn",
  "basePath": "/v1",
  "paths": {
    "/health": {
      "get": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "health"
        ],
        "summary": "Check the health for the site.",
        "operationId": "getHealth",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/HealthStatus"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Error": {
      "required": [
        "code",
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int32"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "HealthStatus": {
      "properties": {
        "status": {
          "type": "string"
        }
      }
    }
  }
}`))
}
